### PR TITLE
Feature/gcb 246 update readme

### PR DESCRIPTION
**Pull request by michallaskowski**
Make sure these boxes are checked before submitting your Pull Request - thank you!

- [x] [SwiftLint](https://github.com/Realm/SwiftLint) is installed on your system
- [x] The project does not generate any warnings or errors
- [x] The tests are passing
- [x] Branch name is in line with [GitFlow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)

### CODE REVIEW

**Comment by michallaskowski** [comment]
I am not sure if we need `Dependencies` section in README. One can always check what's inside podspec.

**Comment by krris** [comment]
I don't know if a lot of people look what's inside podpec 😉  This way is more transparent.

**Comment by fastred** [comment]
But the question is why should it be so transparent? Is it important for most people reading README?

**Comment by krris** [comment]
Sometimes people want to know dependencies of the library and if it uses tons of other libs. To be honest it's not the most important information. We can move it to the end of the README (now it's at the beginning) or remove it.

**Comment by krris** [comment]
@michallaskowski CR is finished. If you want we can remove `Dependencies` section.

**Comment by fastred** [comment]
> Sometimes people want to know dependencies of *the library* and if it uses tons of other libs.

I agree but GCB is more an app than a library 😃.

**Pull request merged**
