### PR TITLE
Fix: 'pod lib lint' warning in GCBUtilities.

### PR DESCRIPTION
**Pull request by krris**
This PR fixes warning while running `pod lib lint GCBUtilities.podspec`.

Make sure these boxes are checked before submitting your Pull Request - thank you!

- [ ] [SwiftLint](https://github.com/Realm/SwiftLint) is installed on your system
- [ ] The project does not generate any warnings or errors
- [ ] The tests are passing
- [ ] Branch name is in line with [GitFlow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)

### CODE REVIEW

**Comment by michallaskowski** [comment]
It's my bad from previous PR (didn't check podspecs).
And there is also a problem with GCBCore.podspec, because it has specified `resource_bundles`. I am not sure how it should be, because there is also a bundle target created in Pods .pbxproj

**Comment by krris** [comment]
`resource_bundles` were removed in https://github.com/macoscope/GrandCentralBoard/pull/183/files. (it's already in `develop`)

**Comment by michallaskowski** [comment]
Ok. But shouldn't we add it to GCBUtilities now? I am not sure, cause it is working without it ;) But maybe then we don't need the additional bundle target, and just these lines in podspec file?

**Comment by michallaskowski** [comment]
Ok, this is addressed in #184

**Pull request merged**
