### PR TITLE
GCB-231: Add `LoadBundledConfig` as EnvironmentVariable.

### PR DESCRIPTION
**Pull request by ochococo**
This is how it's done.

screenshot of xcode 18-04-2016 15-05-35

### CODE REVIEW

**Comment by ochococo** [comment]
**DO NOT MERGE**

**Comment by michallaskowski** [comment]
Works as intended :)

**Comment by michallaskowski** [comment]
@ochococo Please rebase or merge from mvp

**Comment by ochococo** [comment]
@michallaskowski 🎾

**Comment by michallaskowski** [comment]
@ochococo It does not build for me:
```
<unknown>:0: error: filename "NSProcessInfo.swift" used twice: '/Users/michall/macoscope/GrandCentralBoard/GrandCentralBoard/NSProcessInfo.swift' and '/Users/michall/macoscope/GrandCentralBoard/GrandCentralBoard/NSProcessInfo.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "PageViewsRowReport.swift" used twice: '/Users/michall/macoscope/GrandCentralBoard/GrandCentralBoard/Widgets/WebsiteAnalytics/PageViewsRowReport.swift' and '/Users/michall/macoscope/GrandCentralBoard/GrandCentralBoard/Widgets/WebsiteAnalytics/PageViewsRowReport.swift'
```
.xcodeproj file is messed up

**Pull request merged**
