### PR TITLE
Change from `mvp` to `develop`.

### PR DESCRIPTION
**Pull request by ochococo**
Make sure these boxes are checked before submitting your Pull Request - thank you!

- [ ] [SwiftLint](https://github.com/Realm/SwiftLint) is installed on your system
- [ ] The project does not generate any warnings or errors
- [ ] The tests are passing
- [ ] Branch name is in line with [GitFlow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)

### CODE REVIEW

**Comment by michallaskowski** [comment]
Will this be needed with the change from #161 ? Maybe we could delete whole if statement

**Comment by michallaskowski** [comment]
Just checking - we are ok with not running the tests on develop or master?

**Comment by ochococo** [comment]
Tests will run only on PRs right?

**Comment by michallaskowski** [comment]
Good :)

**Pull request merged**
