### PR TITLE
Feature/gcb 276 new design of bonusly widget

### PR DESCRIPTION
**Pull request by krris**
Make sure these boxes are checked before submitting your Pull Request - thank you!

- [x] [SwiftLint](https://github.com/Realm/SwiftLint) is installed on your system
- [x] The project does not generate any warnings or errors
- [x] The tests are passing
- [x] Branch name is in line with [GitFlow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)

### CODE REVIEW

**Comment by ncreated** [comment]
These are not the same gray colors (TR - part of existing clock widget, BL - part of Bonusly widget):

zrzut ekranu 2016-05-18 o 15 09 00

Use `sRGB 32, 32, 32` value for view background.

**Comment by ncreated** [comment]
@krris All good 💪 . Just fix the background color. 🎾

**Comment by ncreated** [comment]
@krris I did the fix. RGB values were fine, the color space was wrong (it was `sRGB`). I changed the activity indicator's container background to `calibraterRGB`. I was wrong in my comment above - we should stick to universal color space when moving colors from Zeplin app.

**Comment by krris** [comment]
@ncreated Nice fix. I've just checked and everything works. I agree that we should use universal color space 👍

**Pull request merged**
